GO ?= go
.PHONY: fmt test vet race build run
fmt:; $(GO)fmt ./...
test:; $(GO) test ./...
vet:; $(GO) vet ./...
race:; $(GO) test -race ./...
build:; $(GO) build ./...
run:; $(GO) run ./cmd/riskd -addr :8123 -data-dir ./data
